# Generated by Django 4.2.20 on 2025-06-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0006_appointment_tips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tips',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Чаевые'),
        ),
    ]
